### ISSUE TITLE
Improve latency of retrieving bytes for BitmapDescriptors in Venues Screen

### ISSUE THREAD

**Issue by nickmeinhold** [enspyrco/crowdleague#29]
- [x] Retrieve bytes asynchronously with simultaneous connections #30 
- [ ] Change to Melbourne bucket, see #4 
- [ ] #23 
- [ ] #21 
- [ ] #25 and only retrieve bytes for icons not in a cluster

Consider using a HttpClient : https://stackoverflow.com/questions/72537615/how-should-i-use-http-clients-for-multiple-connections
> The benefit of reusing an instance of HttpClient is that Dart can then let a connection to stay open for later reuse in case you are going to make another request against the same server.
